---
title: "What is a good way to measure the dispersion or dissimilarity of growth curves?"
authors: "Justin Patterson, Elsa Beda"
output: pdf_document
---

```{r load_packages}
library("ggplot2")
```

```{r Functions}
get_exp_data_with_error = function(max_t, b_0, b_1, b_2, e_0_extremeness, e_1_extremeness, e_2_extremeness) {
    # The model is y = (b_0 + e_0) + (b_1 + e_1)*exp((b_2 + e_2)*t)
    # where e_0, e_1 and e_2 are errors.
    # e_0_extremeness, e_1_extremeness & e_2_extremeness should be non-negative
    # with higher values indicating more extremeness.
    #
    # Returns y values.
    # R is 1-indexed. :(
    y = vector(mode = "numeric", length = max_t + 1)
    
    # It's some proportion of b_0
    sd_0 = e_0_extremeness * abs(b_0)
    e_0 = rnorm(n = max_t + 1, mean = 0, sd = sd_0)

    # Start large and decrease.
    # The part with (- e_1_extremeness * abs(b_1) / max_t)
    # is like the slope.
    sd_1 = e_1_extremeness * abs(b_1) + (- e_1_extremeness * abs(b_1) / max_t) * seq(0, max_t, 1)
    e_1 = rnorm(n = max_t + 1, mean = 0, sd = sd_1)

    sd_2 = e_2_extremeness * abs(b_2)
    e_2 = rnorm(n = max_t + 1, mean = 0, sd = sd_2)

    # y[1] means the y-value when t == 0.
    y[1] = round(b_0 + e_0[1] + b_1 + e_1[1])
    for (t in seq(2, max_t + 1, 1)) {
        y[t] = round((b_0 + e_0[t]) + (y[t - 1] - (b_0 + e_0[t]))*exp(b_2 + e_2[t]))
    }

    return(y)
}

get_growth_data = function(
    num_curves,
    max_t, 
    b_0, 
    b_1, 
    b_2,
    e_0_extremeness,
    e_1_extremeness, 
    e_2_extremeness
) {
    # Before loop
    num_curves_without_extinction = 0
    # Call get_exp_data_with_error to fill g.
    num_rows = max_t + 1
    num_cols = num_curves
    g = matrix(
        data = numeric(length = num_rows * num_cols), 
        nrow = num_rows, 
        ncol = num_cols
    )
    while(num_curves_without_extinction < num_curves) {
        # We need to generate more growth curves.
        new_growth_curve = get_exp_data_with_error(
            max_t = max_t, 
            b_0 = b_0, 
            b_1 = b_1, 
            b_2 = b_2,
            e_0_extremeness = e_0_extremeness,
            e_1_extremeness = e_1_extremeness, 
            e_2_extremeness = e_2_extremeness
        )
        # Prep for next iteration.
        # If there was an extinction, then
        # do not increment num_curves_without_extinction;
        # otherwise, increment num_curves_without_extinction
        # and save the growth curve.

        # If there is at least 1 non-positive value,
        if(sum(new_growth_curve <= 0) > 0) {
            # There was an extinction.
            next 
        } else {
            num_curves_without_extinction = num_curves_without_extinction + 1
            # save curve
            g[, num_curves_without_extinction] = new_growth_curve
        }
    }

    return(g)
}

get_sets_of_growth_data = function(
    num_sets,
    num_curves,
    max_t, 
    b_0, 
    b_1, 
    b_2,
    e_0_extremeness,
    e_1_extremeness, 
    e_2_extremeness
) {
    # Returns a list where each element of the list
    # is a matrix.  Columns in the matrices are
    # the data for the growth curves.
    return(
        replicate(
            n = num_sets,
            expr = get_growth_data(
                num_curves,
                max_t, 
                b_0, 
                b_1, 
                b_2,
                e_0_extremeness,
                e_1_extremeness, 
                e_2_extremeness
            ),
            simplify = FALSE
        )
    )
}

normalized_cv = function(x, na.rm = FALSE) {
    return(sd(x, na.rm) / median(x, na.rm))
}

mean_normalized_cv_of_log_response = function(X) {
    # X: matrix
    #   The columns of X represent independent realizations
    #   of the same discrete-time postive integer-valued 
    #   stochastic process.
    #   The process is assumed to generate ratio data.
    #   Values in the same row of X have the same value
    #   of the index t for the stochastic process.
    #
    # The values in X are transformed via the log
    # function.  The standard deviation of each row
    # of X is computed and divided by the median of
    # each row to yield a normalized coefficient of 
    # variation (CV).
    # https://en.wikipedia.org/wiki/Coefficient_of_variation#Alternative  
    # The CVs of each row are summarized by taking
    # their arithmetic mean.

    return(1 / NROW(X) * sum(apply(X = log(X), MARGIN = 1, FUN = normalized_cv)))
}

mle_var_of_estimator = function(theta_hat, data_generator, n, m, ...) {
    # Estimates the variance of some estimator theta_hat
    # using m trials of the estimator
    # on samples of size n.  The samples are obtained
    # from data_generator.
    # Args:
    #   theta_hat: function. This is the estimator.
    #       It should be able to operate on the 
    #       elements returned in the list by data_generator. 
    #       It should return numeric data of length 1.
    #   data_generator: function. The estimator works
    #       with the data generated by this function.
    #       This function should return a list of length m.
    #       The first argument of this function should be
    #       the equivalent of m as used here, 
    #       while the 2nd argument should be the equivalent of n
    #       as used here.
    #   n: number of samples from population that the estimator
    #       is going to be working with each time.
    #   m: number of replicates to use in estimating the
    #       variance of the estimator.
    #   ... (ellipses) Additional arguments to pass
    #       to theta_hat
    
    m_sets_of_data = data_generator(m, n, ...)

    # For each of the m sets of data,
    # use the estimator theta_hat on each set
    # to get a vector of estimates of length m.
    estimates = vapply(
        X = m_sets_of_data, 
        FUN = theta_hat, 
        FUN.VALUE = numeric(length = 1), 
        USE.NAMES = FALSE
    )

    return(
        (1 / m) * sum(
            (estimates - (1 / m) * sum(estimates))^2
            )
    )
}
```

# Plots of Growth Curves and Estimator

```{r}
# Args for function call
num_sets = 2
num_curves = 5
max_t = 100
b_0 = 1000
b_1 = 100
b_2 = 0.09
e_0_extremeness = 5
e_1_extremeness = 0.1
e_2_extremeness = 0.1

sets_of_growth_curves = get_sets_of_growth_data(
    num_sets = num_sets,
    num_curves = num_curves,
    max_t = max_t, 
    b_0 = b_0, 
    b_1 = b_1, 
    b_2 = b_2,
    e_0_extremeness = e_0_extremeness,
    e_1_extremeness = e_1_extremeness, 
    e_2_extremeness = e_2_extremeness
)


for (i in seq_len(length(sets_of_growth_curves))) {
    g = sets_of_growth_curves[[i]]
    # Make dataframe for graphing with ggplot package.
    g_data = data.frame(
        replicate_num = rep(seq_len(NCOL(g)), each = NROW(g)),
        year = rep(seq(0, NROW(g) - 1), times = NCOL(g)),
        log_pop_size = log(as.vector(g))
    )

    fig = ggplot(
        data = g_data,
        mapping = aes(
            x = year,
            y = log_pop_size,
            color = as.factor(replicate_num)
        )
    ) 

    estimate = round(mean_normalized_cv_of_log_response(g), 4)

    fig_title = paste0("Samples of Growth Curves from the Same Population\nDispersion Estimate: ", estimate)
    fig = fig + 
        geom_line() +
        labs(
            title = fig_title, 
            x = "Year",
            y = "log(Population Size)",
            color = "Replicate"
        ) +
        theme_gray(base_size = 20)

    print(fig)
    fig_file_name = paste0("example_growth_curve_set_", i, ".png")
    ggsave(
        filename = file.path("/home/justin/Documents/schoolwork/ISYE_6413_Design_of_Exp/doe_group_project/data", fig_file_name),
        plot = fig,
        dpi = 800
    )
}
```

# Investigation of Convergence of Growth Curve Dispersion Estimator

```{r}
theta_hat = mean_normalized_cv_of_log_response
data_generator = get_sets_of_growth_data
m = 100
max_t = 100
b_0 = 500
b_1 = 100
b_2 = 0.09
e_0_extremeness = 2
e_1_extremeness = 0.2
e_2_extremeness = 0.9

# Prep before loop
max_n = 30
n = seq(2, max_n, 1)
empirical_variances_of_estimator = vector(mode = "numeric", length = length(n))

for(num_curves in n) {
    # i is an index for empirical_variances_of_estimator
    i = num_curves - 1
    empirical_variances_of_estimator[i] = mle_var_of_estimator(
        theta_hat = theta_hat, 
        data_generator = data_generator,
        n = num_curves,
        m = m,
        max_t = max_t,
        b_0 = b_0,
        b_1 = b_1,
        b_2 = b_2,
        e_0_extremeness = e_0_extremeness,
        e_1_extremeness = e_1_extremeness,
        e_2_extremeness = e_2_extremeness
    )
}
```

```{r}
# https://www.dliebl.com/RM_ES_Script/estimation-theory.html
df_for_estimator_investigation = data.frame(
    n = n,
    empirical_variance_of_estimator = empirical_variances_of_estimator
)
```

Fit power-law model.

```{r}
# https://www.r-bloggers.com/2022/02/how-to-calculate-power-regression-in-r-step-by-step-guide/
model_1 = lm(I(log(empirical_variance_of_estimator)) ~ I(log(n)), data = df_for_estimator_investigation)
summary(model_1)

# https://stackoverflow.com/questions/14033551/r-plotting-confidence-bands-with-ggplot
# https://stackoverflow.com/questions/40324963/when-predicting-using-model-with-logtarget-do-i-have-to-make-any-changes-to-pr
model_1_preds = exp(predict.lm(
    object = model_1,
    newdata = data.frame(n = n)
))

model_1_formula_text = paste0(
    "log(empirical_var_of_estimator) = (", 
    round(exp(coef(model_1)[1]), 4),
    ")(n)^(",
    round(coef(model_1)[2], 4),
    ")"
)
```

```{r}
fig = ggplot(
    data = df_for_estimator_investigation,
    mapping = aes(
        x = n,
        y = empirical_variance_of_estimator
    ) 
)

# https://stackoverflow.com/questions/28755576/add-text-to-ggplot
# https://stackoverflow.com/questions/31568453/using-different-font-styles-in-annotate-ggplot2
fig = fig + geom_line() +
    geom_line(
        data = data.frame(n = n, fit = model_1_preds),
        mapping = aes(x = n, y = fit, color = "red")
    ) +
    scale_y_continuous(n.breaks = 10) +
    # https://stackoverflow.com/questions/65076492/ggplot-size-of-annotate-vs-size-of-element-text
    annotate("text", x = 15, y = 0.002, label = model_1_formula_text, color = "red", size = 8) +
    labs(
        title = "Investigation of Convergence of Growth Curve\nDispersion Estimator",
        y = "Empirical Variance of Estimator"
    ) +
    theme_gray(base_size = 20) +
    guides(color = "none")
    
print(fig)
fig_file_name = paste0("convergence_of_response.png")
ggsave(
    filename = file.path("/home/justin/Documents/schoolwork/ISYE_6413_Design_of_Exp/doe_group_project/data", fig_file_name),
    plot = fig,
    dpi = 800
)
```